# Generated by Django 3.1.7 on 2021-06-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('SHOP_MANAGER', 'SHOP_MANAGER'), ('CUSTOMER', 'CUSTOMER'), ('SUPER_ADMIN', 'SUPER_ADMIN')], max_length=32, verbose_name='user role'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenant.tenant'),
        ),
    ]
