# Generated by Django 3.1.7 on 2021-07-30 00:58

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='strip/train', verbose_name='original image')),
                ('crop_coordinate', models.JSONField(blank=True, null=True, verbose_name='crop coordinate')),
                ('strip_crop', models.ImageField(blank=True, null=True, upload_to='strip/train', verbose_name='image')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('th_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='calcium hardness')),
                ('fc_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='free chlorine')),
                ('tc_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='total chlorine')),
                ('tb_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='total bromine')),
                ('ph_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ph')),
                ('ta_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)], verbose_name='total alkainity')),
                ('ca_value', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='cyanuric acid')),
                ('ch_predict', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='calcium hardness')),
                ('fc_predict', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='free chlorine')),
                ('tc_predict', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='total chlorine')),
                ('tb_predict', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='total bromine')),
                ('ph_predict', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ph')),
                ('ta_predict', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)], verbose_name='total alkainity')),
                ('ca_predict', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)], verbose_name='cyanuric acid')),
            ],
        ),
    ]
