# Generated by Django 3.1.7 on 2021-08-08 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traintesting',
            name='ch_predict',
        ),
        migrations.AddField(
            model_name='traintesting',
            name='th_predict',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='total hardness'),
        ),
    ]
