# Generated by Django 3.1.7 on 2021-06-13 14:33

import core.django.validators
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('abn', models.CharField(max_length=11, validators=[core.django.validators.NumberOnlyValidator()], verbose_name='abn')),
                ('phone_number', models.CharField(blank=True, max_length=16, verbose_name='phone number')),
                ('address1', models.CharField(max_length=250, verbose_name='address1')),
                ('address2', models.CharField(blank=True, max_length=250, verbose_name='address1')),
                ('suburb', models.CharField(max_length=250, verbose_name='suburb')),
                ('city', models.CharField(max_length=250, verbose_name='city')),
                ('post_code', models.CharField(max_length=4, validators=[core.django.validators.NumberOnlyValidator()], verbose_name='post code')),
                ('state', models.CharField(blank=True, choices=[('NSW', 'NSW'), ('VIC', 'VIC'), ('QLD', 'QLD'), ('TAS', 'TAS'), ('WA', 'WA'), ('ACT', 'ACT'), ('NT', 'NT')], max_length=255, verbose_name='state')),
                ('is_active', models.BooleanField(default=True, help_text='Active or in active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_user.user')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('pool_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool_shop.poolshop')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth_user.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth_user.user')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('pool_shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pool_shop.poolshop')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth_user.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
