# Generated by Django 3.1.7 on 2021-06-13 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('pool_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolshop',
            name='tenant',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='tenant.tenant'),
            preserve_default=False,
        ),
    ]
