# Generated by Django 3.1.7 on 2021-06-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool_shop', '0002_poolshop_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='schema_name',
        ),
        migrations.RemoveField(
            model_name='poolshop',
            name='schema_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='schema_name',
        ),
        migrations.AlterField(
            model_name='poolshop',
            name='address2',
            field=models.CharField(blank=True, max_length=250, verbose_name='address2'),
        ),
    ]
